#端口
server:
  port: 8080
  servlet:
    context-path: /demo


#spring连接数据库配置
spring:
  datasource:
    username: root
    password: root
    jdbc-url: jdbc:mysql://localhost:3306/auth?serverTimezone=GMT%2B8&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
          minimum-idle: 5
          idle-timeout: 600000
          maximum-pool-size: 10
          auto-commit: true
          pool-name: MyHikariCP
          max-lifetime: 1800000
          connection-timeout: 30000
          connection-test-query: SELECT 1

#mybatis配置环境
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.xmzpc.demo.dto

#显示sql
logging:
  level:
    com:
      ucar:
        train:
          demo: debug